[package]
name = "adventofcode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
test-case = "*"

[[bin]]
name = "day1"
path = "src/01/main.rs"

[[bin]]
name = "day2"
path = "src/02/main.rs"

[[bin]]
name = "day3"
path = "src/03/main.rs"

[[bin]]
name = "day4"
path = "src/04/main.rs"

[[bin]]
name = "day5"
path = "src/05/main.rs"

[[bin]]
name = "day6"
path = "src/06/main.rs"

[[bin]]
name = "day7"
path = "src/07/main.rs"
